"""initial schema

Revision ID: bd6e57d105df
Revises: 
Create Date: 2026-04-03 17:42:48.268688
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6e57d105df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('nas_ip', sa.String(length=45), nullable=False),
    sa.Column('nas_port', sa.String(length=64), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('bytes_in', sa.Integer(), nullable=False),
    sa.Column('bytes_out', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('command_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('vendor', sa.String(length=128), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('os_type', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('dhcp_fingerprint', sa.String(length=256), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_mac_address'), ['mac_address'], unique=True)

    op.create_table('guest_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_sessions_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_sessions_token'), ['token'], unique=True)

    op.create_table('nas_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('nas_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nas_clients_ip_address'), ['ip_address'], unique=False)

    op.create_table('tacacs_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tacacs_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tacacs_clients_ip_address'), ['ip_address'], unique=False)

    op.create_table('tacacs_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('packet_type', sa.Enum('AUTHEN', 'AUTHOR', 'ACCTING', name='tacacspackettype'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=False),
    sa.Column('nas_port', sa.String(length=64), nullable=False),
    sa.Column('privilege_level', sa.Integer(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tacacs_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tacacs_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_tacacs_logs_username'), ['username'], unique=False)

    op.create_table('vlan_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('command_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_set_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('PERMIT', 'DENY', name='commandruleaction'), nullable=False),
    sa.Column('command_pattern', sa.String(length=256), nullable=False),
    sa.Column('args_pattern', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['command_set_id'], ['command_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('command_set_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['command_set_id'], ['command_sets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('action', sa.Enum('PERMIT', 'DENY', 'GUEST', name='policyaction'), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('nas_ip', sa.String(length=45), nullable=False),
    sa.Column('nas_port', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.Enum('PAP', 'CHAP', 'PEAP', 'EAP_TLS', 'MAB', 'WEB_AUTH', 'PAP_CHAP', name='authmethod'), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', 'CHALLENGE', name='authresult'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('policy_name', sa.String(length=128), nullable=False),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_logs_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_logs_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_logs_username'))
        batch_op.drop_index(batch_op.f('ix_auth_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_auth_logs_mac_address'))

    op.drop_table('auth_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('policies')
    op.drop_table('groups')
    op.drop_table('command_rules')
    op.drop_table('vlan_mappings')
    with op.batch_alter_table('tacacs_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tacacs_logs_username'))
        batch_op.drop_index(batch_op.f('ix_tacacs_logs_timestamp'))

    op.drop_table('tacacs_logs')
    with op.batch_alter_table('tacacs_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tacacs_clients_ip_address'))

    op.drop_table('tacacs_clients')
    with op.batch_alter_table('nas_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nas_clients_ip_address'))

    op.drop_table('nas_clients')
    with op.batch_alter_table('guest_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_sessions_token'))
        batch_op.drop_index(batch_op.f('ix_guest_sessions_mac_address'))

    op.drop_table('guest_sessions')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_mac_address'))

    op.drop_table('devices')
    op.drop_table('command_sets')
    op.drop_table('admin_users')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_session_id'))

    op.drop_table('active_sessions')
    # ### end Alembic commands ###
